import { Bell, CheckCircle2, Download, FileBarChart, Plus, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { jsonBody, request } from "../api";

function PageHeader({ eyebrow, title, copy, action }: { eyebrow: string; title: string; copy: string; action?: React.ReactNode }) {
  return <header className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{copy}</p></div>{action}</header>;
}
function date(value?: string) { return value ? new Date(value).toLocaleDateString() : "—"; }

export function ApprovalsPage() {
  const [rows, setRows] = useState<any[]>([]); useEffect(() => { request<any[]>("/api/internal/approvals").then(setRows); }, []);
  return <div className="page-stack"><PageHeader eyebrow="Decision workflow" title="Approval inbox" copy="Findings awaiting reviewer or management action." /><section className="panel table-panel"><div className="responsive-table"><table><thead><tr><th>Case</th><th>Complaint</th><th>Risk</th><th>Stage</th><th>Version</th><th>Updated</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.case_id}><td><Link className="case-link" to={`/portal/cases/${row.case_id}`}>{row.case_id}</Link></td><td>{row.title}</td><td><span className={`badge risk-${String(row.risk_rating).toLowerCase()}`}>{row.risk_rating}</span></td><td>{row.status}</td><td>v{row.version}</td><td>{date(row.updated_at)}</td><td><Link className="button button-small" to={`/portal/cases/${row.case_id}`}>Review</Link></td></tr>)}</tbody></table>{!rows.length && <div className="empty-state">No approvals are waiting.</div>}</div></section></div>;
}

export function ActionsPage() {
  const [rows, setRows] = useState<any[]>([]); const [error, setError] = useState("");
  const load = () => request<any[]>("/api/internal/corrective-actions").then(setRows).catch((cause: Error) => setError(cause.message));
  useEffect(() => { void load(); }, []);
  const update = async (actionId: string, status: string) => { const progressUpdate = window.prompt("Enter a progress update or reason:"); if (!progressUpdate) return; await request(`/api/internal/corrective-actions/${actionId}`, { method: "PATCH", ...jsonBody({ status, progressUpdate }) }); load(); };
  const verify = async (actionId: string, decision: string) => { if (!window.confirm(`${decision} and record this verification decision?`)) return; const remarks = window.prompt("Mandatory verification remarks:"); if (!remarks) return; await request(`/api/internal/corrective-actions/${actionId}/verify`, { method: "POST", ...jsonBody({ decision, remarks }) }); load(); };
  return <div className="page-stack"><PageHeader eyebrow="Remediation oversight" title="Corrective action register" copy="Monitor ownership, evidence, verification and overdue actions." />{error && <div className="notice error">{error}</div>}<section className="action-cards">{rows.map((row) => <article className={`action-card ${row.is_overdue ? "overdue" : ""}`} key={row.id}><div><span className="case-id">{row.action_id}</span><span className="badge">{row.status}</span></div><h2>{row.recommendation}</h2><p><b>{row.case_id}</b> · {row.case_title}</p><dl className="detail-grid"><div><dt>Owner</dt><dd>{row.owner_name}</dd></div><div><dt>Department</dt><dd>{row.responsible_department}</dd></div><div><dt>Priority</dt><dd>{row.priority}</dd></div><div><dt>Target</dt><dd>{date(row.target_date)}{row.is_overdue ? " · Overdue" : ""}</dd></div></dl><div className="button-row"><button className="button button-secondary button-small" onClick={() => update(row.action_id, "In Progress")}>Update progress</button><button className="button button-secondary button-small" onClick={() => update(row.action_id, "Pending Verification")}>Submit evidence</button>{row.status === "Pending Verification" && <><button className="button button-small" onClick={() => verify(row.action_id, "Approve")}>Verify</button><button className="button button-danger button-small" onClick={() => verify(row.action_id, "Reject")}>Reject</button></>}</div></article>)}{!rows.length && <div className="panel empty-state">No corrective actions are assigned or visible.</div>}</section></div>;
}

export function ReportsPage() {
  return <div className="page-stack"><PageHeader eyebrow="Management information" title="Reports and exports" copy="Authorised, permission-filtered reporting without unnecessary complainant details." action={<a className="button" href="/api/internal/reports/export.csv"><Download size={17} /> Export filtered CSV</a>} /><section className="report-grid">{[["Monthly complaint report", "Volume, categories, risk and current disposition."], ["Quarterly management report", "Trends, outcomes, SLA and department distribution."], ["SLA compliance report", "Upcoming, overdue and extended deadlines."], ["Risk category report", "Critical and high-risk exposure by allegation type."], ["Case officer workload", "Open assignments, due dates and investigation stage."], ["Corrective action report", "Ownership, overdue actions and verification status."]].map(([title, copy]) => <article className="panel report-card" key={title}><span className="large-icon"><FileBarChart /></span><h2>{title}</h2><p>{copy}</p><a href="/api/internal/reports/export.csv">Generate report →</a></article>)}</section><div className="notice"><ShieldCheck size={19} /><p>Exports intentionally omit complainant contact details and full complaint narratives. Case visibility is applied server-side.</p></div></div>;
}

export function NotificationsPage() {
  const [rows, setRows] = useState<any[]>([]); const load = () => request<any[]>("/api/internal/notifications").then(setRows); useEffect(() => { void load(); }, []);
  const markRead = async (id: string) => { await request(`/api/internal/notifications/${id}/read`, { method: "POST", ...jsonBody({}) }); load(); };
  return <div className="page-stack"><PageHeader eyebrow="Work queue" title="Notifications" copy="Assignments, SLA alerts, approvals and corrective-action updates." /><section className="panel notification-list">{rows.map((item) => <article className={item.read_at ? "read" : ""} key={item.id}><span className="notification-icon">{item.read_at ? <CheckCircle2 /> : <Bell />}</span><div><b>{item.subject}</b><p>{item.body}</p><small>{new Date(item.created_at).toLocaleString()} · {item.delivery_status}</small></div><div>{item.action_url && <Link className="button button-small button-secondary" to={item.action_url}>Open</Link>}{!item.read_at && <button className="link-button" onClick={() => markRead(item.id)}>Mark read</button>}</div></article>)}{!rows.length && <div className="empty-state">No notifications.</div>}</section></div>;
}

export function UsersPage() {
  const [rows, setRows] = useState<any[]>([]); const [showForm, setShowForm] = useState(false); const [message, setMessage] = useState("");
  const load = () => request<any[]>("/api/internal/users").then(setRows); useEffect(() => { void load(); }, []);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await request("/api/internal/users", { method: "POST", ...jsonBody({ email: form.get("email"), displayName: form.get("displayName"), department: form.get("department"), roles: form.getAll("roles") }) }); setMessage("User created."); setShowForm(false); load(); };
  return <div className="page-stack"><PageHeader eyebrow="Access governance" title="Users and roles" copy="Authorised identities and server-enforced role assignments." action={<button className="button" onClick={() => setShowForm(!showForm)}><Plus size={17} /> Add user</button>} />{message && <div className="notice success">{message}</div>}{showForm && <form className="panel admin-form" onSubmit={submit}><h2>Add authorised user</h2><div className="form-grid"><label>Display name<input name="displayName" required /></label><label>Organisation email<input name="email" type="email" required /></label><label>Department<input name="department" /></label></div><label>Roles<select name="roles" multiple required size={8}>{["SYSTEM_ADMINISTRATOR", "INTEGRITY_ADMINISTRATOR", "INTEGRITY_OFFICER", "CASE_OFFICER", "REVIEWER", "MANAGEMENT_APPROVER", "DEPARTMENT_ACTION_OWNER", "AUDITOR"].map((role) => <option key={role}>{role}</option>)}</select></label><button className="button">Create user</button></form>}<section className="panel table-panel"><div className="responsive-table"><table><thead><tr><th>User</th><th>Department</th><th>Roles</th><th>Status</th></tr></thead><tbody>{rows.map((user) => <tr key={user.id}><td><b>{user.display_name}</b><small>{user.email}</small></td><td>{user.department ?? "—"}</td><td>{String(user.roles ?? "").split(",").map((role) => <span className="badge" key={role}>{role.replaceAll("_", " ")}</span>)}</td><td>{user.active ? "Active" : "Disabled"}</td></tr>)}</tbody></table></div></section></div>;
}

export function SettingsPage() {
  const [data, setData] = useState<any>(null); const [message, setMessage] = useState(""); const load = () => request("/api/internal/settings").then(setData); useEffect(() => { void load(); }, []);
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); await request("/api/internal/settings/sla", { method: "PUT", ...jsonBody({ riskLevel: form.get("riskLevel"), categoryId: null, targetBusinessDays: Number(form.get("targetBusinessDays")) }) }); setMessage("SLA rule updated."); load(); };
  return <div className="page-stack"><PageHeader eyebrow="Platform configuration" title="System settings" copy="SLA targets, evidence policy and operational controls." />{message && <div className="notice success">{message}</div>}<div className="case-grid"><section className="panel wide"><h2>SLA rules</h2><div className="responsive-table"><table><thead><tr><th>Risk</th><th>Category</th><th>Business days</th><th>Active</th></tr></thead><tbody>{data?.slaRules.map((rule: any) => <tr key={rule.id}><td>{rule.risk_level}</td><td>{rule.category_name ?? "All categories"}</td><td>{rule.target_business_days}</td><td>{rule.active ? "Yes" : "No"}</td></tr>)}</tbody></table></div></section><form className="action-form" onSubmit={save}><h3>Update default SLA</h3><label>Risk level<select name="riskLevel"><option>Critical</option><option>High</option><option>Medium</option><option>Low</option></select></label><label>Target business days<input name="targetBusinessDays" type="number" min="1" max="365" required /></label><button className="button">Update rule</button></form></div><section className="panel"><h2>Operational policy</h2><div className="settings-list">{data?.settings.map((setting: any) => <div key={setting.setting_key}><b>{setting.setting_key.replaceAll("_", " ")}</b><code>{setting.setting_value}</code><small>Updated {date(setting.updated_at)}</small></div>)}</div></section></div>;
}

export function AuditPage() {
  const [rows, setRows] = useState<any[]>([]); useEffect(() => { request<any[]>("/api/internal/audit").then(setRows); }, []);
  return <div className="page-stack"><PageHeader eyebrow="Immutable accountability" title="Audit log" copy="Security-relevant actions, correlation IDs and business reasons. Records cannot be edited or deleted." /><section className="panel table-panel"><div className="responsive-table"><table><thead><tr><th>Timestamp</th><th>Action</th><th>Entity</th><th>User</th><th>Reason</th><th>Correlation ID</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{new Date(row.timestamp).toLocaleString()}</td><td><b>{row.action.replaceAll("_", " ")}</b><small>{row.source}</small></td><td>{row.entity_type}<small>{row.entity_id}</small></td><td>{row.user_name ?? "System / public"}</td><td>{row.reason ?? "—"}</td><td><code>{row.correlation_id}</code></td></tr>)}</tbody></table></div></section></div>;
}
